x-environment:
  &default-back-environment
  # These environment variables will be used by taiga-back and taiga-async.
  POSTGRES_DB: "taiga"
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_HOST: "taiga-db"
  TAIGA_SECRET_KEY: "${SECRET_KEY}"
  TAIGA_SITES_SCHEME: "http"
  TAIGA_SITES_DOMAIN: "localhost:9000"


  # --- CONFIGURAZIONE EMAIL REALI (SMTP) ---
  TAIGA_SUBPATH: "${SUBPATH}"
  EMAIL_BACKEND: "django.core.mail.backends.${EMAIL_BACKEND}.EmailBackend"
  DEFAULT_FROM_EMAIL: "taiga-notify@gmail.com"        # indirizzo mittente
  EMAIL_USE_TLS: "True"                               # Gmail usa TLS
  EMAIL_USE_SSL: "False"
  EMAIL_HOST: 64.233.167.109                   # smtp.gmail.com risolve in questo IP
  EMAIL_PORT: 587 #"${EMAIL_PORT}"
  EMAIL_HOST_USER: "raheladoc23@gmail.com"           # il tuo account
  EMAIL_HOST_PASSWORD:  "thwruylduoqxavyz"         # password o token app

  # RabbitMQ configuration for async tasks
  RABBITMQ_USER: "${RABBITMQ_USER}"
  RABBITMQ_PASS: "${RABBITMQ_PASS}"
  RABBITMQ_VHOST: "${RABBITMQ_VHOST:-taiga}"
  RABBITMQ_HOST: "taiga-async-rabbitmq"
  CELERY_BROKER_URL: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@taiga-async-rabbitmq:5672/${RABBITMQ_VHOST}"

  ENABLE_TELEMETRY: "${ENABLE_TELEMETRY}"

x-volumes:
  &default-back-volumes
  - taiga-docker_taiga-static-data:/taiga-back/static
  - taiga-docker_taiga-media-data:/taiga-back/media

services:
  taiga-db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: "taiga"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - taiga-docker_taiga-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 2s
      timeout: 15s
      retries: 5
      start_period: 3s
    networks:
      - taiga
    ports:
      - "5432:5432"  # Porta DB esposta sul PC

  taiga-back:
    image: taigaio/taiga-back:latest
    environment:
      <<: *default-back-environment
      TAIGA_EVENTS_URL: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@taiga-events-rabbitmq:5672/${RABBITMQ_VHOST}"
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      taiga-db:
        condition: service_healthy
      taiga-events-rabbitmq:
        condition: service_started
      taiga-async-rabbitmq:
        condition: service_started
    ports:
      - "8000:8000"  # Porta back esposta sul PC

  taiga-async:
    image: taigaio/taiga-back:latest
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      taiga-db:
        condition: service_healthy
      taiga-events-rabbitmq:
        condition: service_healthy
      taiga-async-rabbitmq:
        condition: service_healthy
    ports:
      - "8001:8000"  # Async esposto sul PC

  taiga-async-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    hostname: "taiga-async-rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
      RABBITMQ_DEFAULT_VHOST: "${RABBITMQ_VHOST}"
    healthcheck:
      test: ["CMD",  "rabbitmqctl",  "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 3s
    networks:
      - taiga
    ports:
      - "5672:5672"
      - "15672:15672"

  taiga-front:
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_URL: "${TAIGA_SCHEME}://${TAIGA_DOMAIN}"
      TAIGA_WEBSOCKETS_URL: "${WEBSOCKETS_SCHEME}://${TAIGA_DOMAIN}"
      TAIGA_SUBPATH: "${SUBPATH}"
    networks:
      - taiga
    ports:
      - "8080:80"  # Frontend esposto sul PC

  taiga-events:
    image: taigaio/taiga-events:latest
    environment:
      RABBITMQ_USER: "${RABBITMQ_USER}"
      RABBITMQ_PASS: "${RABBITMQ_PASS}"
      TAIGA_SECRET_KEY: "${SECRET_KEY}"
      TAIGA_EVENTS_RABBITMQ_HOST: "taiga-events-rabbitmq"
      TAIGA_EVENTS_RABBITMQ_PORT: "5672"
    networks:
      - taiga
    depends_on:
      taiga-events-rabbitmq:
        condition: service_started
    ports:
      - "8888:8888"

  taiga-events-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
      RABBITMQ_DEFAULT_VHOST: "${RABBITMQ_VHOST}"
    hostname: "taiga-events-rabbitmq"
    volumes:
      - taiga-docker_taiga-events-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga
    ports:
      - "5673:5672"
      - "15673:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  taiga-protected:
    image: taigaio/taiga-protected:latest
    environment:
      MAX_AGE: "${ATTACHMENTS_MAX_AGE}"
      SECRET_KEY: "${SECRET_KEY}"
    networks:
      - taiga
    ports:
      - "8003:8003"

  taiga-gateway:
    image: nginx:1.19-alpine
    ports:
      - "9000:80"
    volumes:
      - ./taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
      - taiga-docker_taiga-static-data:/taiga/static
      - taiga-docker_taiga-media-data:/taiga/media
    networks:
      - taiga
    depends_on:
      - taiga-front
      - taiga-back
      - taiga-events

volumes:
  taiga-docker_taiga-db-data:
  taiga-docker_taiga-static-data:
  taiga-docker_taiga-media-data:
  taiga-docker_taiga-async-rabbitmq-data:
  taiga-docker_taiga-events-rabbitmq-data:

networks:
  taiga:
